# Generated by Django 5.2.3 on 2025-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(help_text='Enter one ingredients per line')),
                ('instructions', models.TextField(help_text='Enter instructions step by step')),
                ('preparation_time', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('cooking_time', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
